module.exports = global.config = {
  app_version: '2.0.19',
  api_host: 'https://daepo.pe.kr/',
  user_info_const: {
    TOKEN: 0,
    UID: 1,
    NICKNAME: 2,
    AVATA: 3,
    BIRTHDATE: 4,
    BELONG: 5,
    DEPARTMENT: 6,
    GENDER: 7,
    VERIFIED: 8,
    YAMI: 9,
    LOCATION: 10,
    HEIGHT: 11,
    NEW_FRIEND_REQUESTS: 12,
    FREE: 15,
  },
};
